src/Entity/Book.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\Book\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    use EntityTrait, TimestampableEntityTrait;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column]
    private ?int $number_page = null;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getNumberPage(): ?int
    {
        return $this->number_page;
    }

    public function setNumberPage(int $number_page): static
    {
        $this->number_page = $number_page;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('author')
            ->add('number_page')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\DTO\BooK\CreateBookDto;
use App\DTO\BooK\UpdateBookDto;
use App\Entity\Book;
use App\Form\BookType;
use App\Service\Book\BookServiceInterface;
use App\Validator\FormRequestValidatorInterface;
use App\ValueObject\Book\BookListRequestData;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/book')]
class BookController extends AbstractController
{
    public function __construct(
        private readonly BookServiceInterface $bookService,
        private readonly FormRequestValidatorInterface $formRequestValidator,
    ) {
    }

    #[Route('/', name: 'app_book_index', methods: ['GET'])]
    public function index(Request $request): Response
    {
        $requestData = BookListRequestData::createFromRequest($request);

        $response = $this->bookService->list($requestData);

        return $this->render('book/index.html.twig', $response->toArray());
    }

    /**
     * @throws HttpExceptionInterface
     */
    #[Route('/new', name: 'app_book_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $form = $this->formRequestValidator
            ->validate($request, BookType::class);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->bookService->create($form->getData());

            return $this->redirectToRoute('app_book_index', [],
                Response::HTTP_SEE_OTHER);
        }

        $response = CreateBookDto::responseData($form);

        return $this->render('book/new.html.twig', $response->toArray());
    }

    #[Route('/{id}', name: 'app_book_show', methods: ['GET'])]
    public function show(Book $book): Response
    {
        return $this->render('book/show.html.twig', ['book' => $book]);
    }

    /**
     * @throws HttpExceptionInterface
     */
    #[Route('/{id}/edit', name: 'app_book_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Book $book): Response
    {
        $form = $this->formRequestValidator
            ->validate($request, BookType::class, $book);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->bookService->update();

            return $this->redirectToRoute('app_book_index', [],
                Response::HTTP_SEE_OTHER);
        }

        $response = UpdateBookDto::responseData($form);

        return $this->render('book/edit.html.twig', $response->toArray());
    }

    #[Route('/{id}', name: 'app_book_delete', methods: ['POST'])]
    public function delete(Request $request, Book $book): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(),
            $request->request->get('_token'))) {
            $this->bookService->delete($book);
        }

        return $this->redirectToRoute('app_book_index', [],
            Response::HTTP_SEE_OTHER);
    }
}

templates/book/_delete_form.html.twig
<form method="post" action="{{ path('app_book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Delete</button>
</form>

templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book{% endblock %}

{% block body %}
    <h1>Edit Book</h1>

    {{ include('book/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_book_index') }}">back to list</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book index{% endblock %}

{% block body %}
    <h1>Book index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Author</th>
                <th>Number_page</th>
                <th>Id</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.numberPage }}</td>
                <td>{{ book.id }}</td>
                <td>{{ book.createdAt ? book.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ book.updatedAt ? book.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_book_show', {'id': book.id}) }}">show</a>
                    <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_book_new') }}">Create new</a>
{% endblock %}

templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Book{% endblock %}

{% block body %}
    <h1>Create new Book</h1>

    {{ include('book/_form.html.twig') }}

    <a href="{{ path('app_book_index') }}">back to list</a>
{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book{% endblock %}

{% block body %}
    <h1>Book</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Title</th>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ book.description }}</td>
            </tr>
            <tr>
                <th>Author</th>
                <td>{{ book.author }}</td>
            </tr>
            <tr>
                <th>Number_page</th>
                <td>{{ book.numberPage }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ book.createdAt ? book.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ book.updatedAt ? book.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_book_index') }}">back to list</a>

    <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}